var vegetarian="Lots of mushrooms, black olives, bell peppers, onions, artichoke hearts and\nfresh tomatoes. "
var hawaiian="Overloaded with juicy pineapple, smoked bacon, sliced ham, on a cheesy\nParmesan crust."
var meatlovers="Loads of pepperoni, savory italian sausage, smoked bacon, hamburger,\nmushrooms, and extra cheese."
var theworks="An irresistable combination of pepperoni, ham, spicy italian sausage,\nfresh-sliced onions and green peppers, gourmet baby portabella mushrooms, and ripe black olives."
var fourcheese="Thin-crust pizza with a four-cheese blend of Mozarella, Parmesan, Roman,\nand Asiago, along with our special seasoning."
